### ISSUE TITLE
`signed` keyword is not supported.

### ISSUE THREAD

**Issue by Sh4rK** [tree-sitter/tree-sitter-c#10]
While the `unsigned` keyword works, its counterpart, `signed` doesn't.

It seems like a one-line addition at https://github.com/tree-sitter/tree-sitter-c/blob/b7fb8b969171040fc7043d63e9b2b3f24f95954f/grammar.js#L284-L288

**Comment by maxbrunsfeld** [comment]
Thanks for raising this!
