### ISSUE TITLE
Error with macros in parameter_list

### ISSUE THREAD

**Issue by m-demare** [tree-sitter/tree-sitter-c#100]
Hi, I've received [this](https://github.com/m-demare/hlargs.nvim/issues/21) issue in my neovim plugin

Basically, when a macro is used in the parameter_list, the parser fails:
![imagen](https://user-images.githubusercontent.com/34817965/164526644-2b7c6b6e-f098-4ab8-8ba6-0a0f5b777a67.png)

Is this solvable?

**Comment by amaanq** [comment]
no not exactly, tree-sitter doesn't do well with macros

**Comment by m-demare** [comment]
Okay, thanks for the response! Neovim got LSP tokens recently, so this isn't as big of an issue anymore
