### ISSUE TITLE
C precedence bugs

### ISSUE THREAD

**Issue by hlandau** [tree-sitter/tree-sitter-c#101]
Using the following in the playground leads to an inaccurate parse:

```c
int f(void) {
  return a *= b != c ? d : e;
}
```
This parses as `(a*=(b!=c))?d:e`, not `a *= ((b!=c) ? d : e)`.

Proof: https://gcc.godbolt.org/z/dqYYnbcE4

Another misparse is `a(b) >> c &= d`.

Reported thanks to [atk](https://lobste.rs/s/4z37uj/game_for_learning_c_operator_precedence#c_zh2gwl)

**Comment by amaanq** [comment]
Is `a(b) >> c &= d` even valid? It's not a correct LHS of an assignment expression in godbolt

**Comment by hlandau** [comment]
Probably not, but I suppose that's orthogonal to the question of how it should parse.

Thanks for the fix!

**Comment by amaanq** [comment]
Well not exactly imo, if some code is invalid you can't exactly ensure error recovery parsing will ensure intact precedence. If you have a sample that parses without error now that's something to work with
