### ISSUE TITLE
Variable names with single capital letter aren't highlighted as constant

### ISSUE THREAD

**Issue by WieeRd** [tree-sitter/tree-sitter-c#104]
![image](https://user-images.githubusercontent.com/59733058/170888751-bf162e29-e36d-40e7-9f80-6b3255dbcc43.png)

This occurs in both C/C++.  
Captured in Neovim v0.7.0 using nvim-treesitter.

**Comment by jdrouhard** [comment]
This is not a parser issue. Open an issue on the nvim-treesitter repo if you wish.
