### ISSUE TITLE
for_statement has no 'body' field just bare $._statement

### ISSUE THREAD

**Issue by dan1338** [tree-sitter/tree-sitter-c#109]
As the title suggests,
The grammar doesn't specify a field('body', ...) in for_statement definition, it's just a bare $._statement.
This goes contrary to for example, the while_statement, do_statement, switch_statement etc.

Is that a conscious decision or just a mistake?
Hopefully it's the latter and can be easily fixed, because as of right now accessing that node from its parent requires a lot of obviously hacky code.

**Comment by jdrouhard** [comment]
Closed by #110
