### ISSUE TITLE
"Array" form function parameters are not recognized

### ISSUE THREAD

**Issue by distobs** [tree-sitter/tree-sitter-c#116]
I am using neovim with nvim-treesitter.

In this function:

`int foo(char bar[], int baz);`

bar is not highlighted as a parameter, unlike baz, which actually is recognized as such.

Strangely, in

`int bar(char *foo[], int foobaz);`,

both parameters are recognized and highlighted.

**Comment by amaanq** [comment]
belongs in nvim-treesitter
