### ISSUE TITLE
Handling form feed character

### ISSUE THREAD

**Issue by casouri** [tree-sitter/tree-sitter-c#117]
The parser is awesome! However, it sometimes chokes on [form feed character](https://en.wikipedia.org/wiki/Page_break), which is used in source files from time to time. The grammar should treat it as whitespace.

**Comment by amaanq** [comment]
Do you have an example of where it could choke?

**Comment by casouri** [comment]
First of all, it's parsed as an error node in the parser. I remember seeing it cause some problem but I couldn't find the example now, sorry about that. I put together an example of a typical usage of form feed character in source files: put before a section header comment for delimiting sections.

```c
int main() {
  return 0;
}


/* Section header */


int subr() {
  return 1;
}
```
