### ISSUE TITLE
Cyclic path in the parse tree

### ISSUE THREAD

**Issue by casouri** [tree-sitter/tree-sitter-c#119]
I encountered a case where a node's sibling's parent is the node itself. I don't know if this is a tree-sitter bug or a tree-sitter-c bug, but here it is:

For a program like this:
```C
#ifdef A
struct a{
};
```
the parse tree is
```
(preproc_ifdef #ifdef name: (identifier)
 (struct_specifier struct name: (type_identifier)
  body: (field_declaration_list { }))
 ; #endif)
```

And if we go from the semicolon, first find its next sibling, which is the `#endif`, then the parent of `#endif`, and we are back at the semicolon.

To reproduce, try the following python script. (`libtree-sitter-c.dylib` needs to be in the same directory as the script.) I'm using tree-sitter-c built from latest master, and python's tree-sitter binding on PyPI, so 0.20.1. I first observed this in Emacs, and it uses tree-sitter v0.20.7.

```python
from tree_sitter import Language, Parser
import tree_sitter

LANG = Language('libtree-sitter-c.dylib', 'c')
parser = Parser()
parser.set_language(LANG)

text = '''#ifdef A
struct a{
};
'''

tree = parser.parse(bytes(text, "utf8"))

root_node = tree.root_node

query = LANG.query('";" @cap')

captures = query.captures(tree.root_node)

semicolon = captures[0][0]

semicolon.next_sibling.parent == semicolon
```
which evaluates to True.

**Comment by maxbrunsfeld** [comment]
I think this is a bug in the `ts_node_parent` method, that occurs when a node has zero extent (such as the *missing* `#endif` token in this tree). It's pretty bad; it'll require making `ts_node_parent` a bit more complex to fix.

**Comment by casouri** [comment]
Ok, I looked at the source of `ts_node_prev_sibling`, it seems the only way to traverse backwards is to traverse forwards and stop at the node just before the starting node. I don't have any questions now. Thanks :-)

**Comment by jdtsmith** [comment]
In at least one context — emacs with `python-ts-mode`, navigating from a node at point up to root — `ts_node_parent` is quite a bit faster and scales _much better_ (logarithmic with line number) than `ts_tree_cursor_goto_parent`, the latter growing in time used by over 100x from beginning to end of a large (>8k line) file.

[Test results here](https://gist.github.com/jdtsmith/7fa6263a13559d587abb51827e6ae472?permalink_comment_id=4665645#gistcomment-4665645).  Perhaps the [current emacs 29 implementation](https://github.com/emacs-mirror/emacs/blob/9e0524a8820fbb8fdb155b1ca58919dcfcaffd63/src/treesit.c#L1893-L1913) of node-parent using cursors is sub-optimal in some way?
