### ISSUE TITLE
token parsed as 'type_identifier' only if token has at least 6 chars

### ISSUE THREAD

**Issue by pksadiq** [tree-sitter/tree-sitter-c#121]
token in an incomplete source is parsed as 'type_identifier' only if token has at least 6 (sometimes 5) chars, this happens only if the block is empty.

```c
int
main (void)
{
  _Bool
}
```

Generated tree from [playground](https://tree-sitter.github.io/tree-sitter/playground):

```octave
translation_unit [0, 0] - [6, 0]
  function_definition [0, 0] - [4, 1]
    type: primitive_type [0, 0] - [0, 3]
    declarator: function_declarator [1, 0] - [1, 11]
      declarator: identifier [1, 0] - [1, 4]
      parameters: parameter_list [1, 5] - [1, 11]
        parameter_declaration [1, 6] - [1, 10]
          type: primitive_type [1, 6] - [1, 10]
    body: compound_statement [2, 0] - [4, 1]
      ERROR [3, 2] - [3, 7]
        identifier [3, 2] - [3, 7]
```

Here, `_Bool` is identified as an `identifier`, but it should Ideally be `type_identifier` at least (precisely it is `primitive_type` though). There is no issue parsing it right if there is at least one statement preceding the `_Bool` (`_Bool` is just an example, and it can be a custom `typedef`).

**Comment by pksadiq** [comment]
This seems to also happen in file scope with empty content:

Eg: If I want to type `RealType`,  The token is identified as an `identifier` until `RealT` and as `type_identifier` thereafter.

**Comment by amaanq** [comment]
it seems to be consistently identifier with 4 or 6 chars now, while not ideal, it makes sense as the code is incomplete - if you're suggesting to add _Bool to primitive_type that's a different story though

**Comment by pksadiq** [comment]
I have had a hack around treesitter to configure my Emacs do what I mean based on whether the preceding token is an identifier or not. I have changed the logic to something different.

So I'm no longer in need of this. Feel Free to close.

thanks,
Mohammed Sadiq
