### ISSUE TITLE
Question: use tree-sitter-cpp all the time?

### ISSUE THREAD

**Issue by genotrance** [tree-sitter/tree-sitter-c#15]
I'm assuming tree-sitter-cpp is a superset of everything in tree-sitter-c. Is there any issues with using tree-sitter-cpp on C files as well?

This will avoid a bunch of flags, detection and what not in [nimterop](https://github.com/genotrance/nimterop].

Thank you.

**Comment by timotheecour** [comment]
one issue with that approach is it won't detect illegal C things that is legal C++ thing

**Comment by genotrance** [comment]
I'm not certain if tree-sitter actually handles that scenario. Will be great if @maxbrunsfeld could comment on this.

**Comment by maxbrunsfeld** [comment]
Certain C constructs are removed from the C++ parser, like the `auto` storage class specifier, and parsing of function-like macros that evaluate to a type (because that's not a common idiom in C++ since C++ has templates).

Those things might not matter to you though. 🤷‍♂️
