### ISSUE TITLE
Large C Macros Over Multiple Lines Causes Either Loads Forever or SegFaults

### ISSUE THREAD

**Issue by VictorSohier** [tree-sitter/tree-sitter-c#159]
## Problem

Whenever I load a specific file with a large C macro (I'm messing around with generic collections), and I open the file either by the editor or via telescope preview, neovim either ceases, or at one point, just segfaults. Another symptom is that there seems to be excessive memory usage upon opening this file (16 GiB, the file is about 13KiB).

## Steps to Reproduce

Open [list.h](https://github.com/VictorSohier/ccollections/blob/master/include/list.h) in neovim with [my config](https://github.com/VictorSohier/nvim). I have isolated this to nvim-treesitter already, but wanted to post the issue here first and work my way up the chain.

## Expected Behavior

The ability to actually edit filles with huge macros without disabling treesitter.

System Information:
Neovim version: 0.9.1-3.1
Operating system: Cachyos, Linux version 6.1.8-1-cachyos-cacule
Installation: cachyos-extra-v3/neovim via yay
Terminal:
- Kitty 0.29.2 (xterm-kitty)
- xfce4-terminal 1.0.4 (xterm-256color)

**Comment by amaanq** [comment]
Doesn't belong here
