### ISSUE TITLE
Allow dollar sign ($) in identifier names

### ISSUE THREAD

**Issue by btuin** [tree-sitter/tree-sitter-c#166]
Some codes may use a dollar in an identifier name ([https://gcc.gnu.org/onlinedocs/gcc/Dollar-Signs.html](https://gcc.gnu.org/onlinedocs/gcc/Dollar-Signs.html)).

While not part of the standard, this is decently supported among compilers, as it seems that GCC, Clang, and MSVC support it.

Also it would honestly be pretty convenient for me, as I'm developing a [grammar for Flex/Bison](https://gitlab.com/btuin2/tree-sitter-bison) and they use extensively the dollar sign in C code.

It should be easy to support, I think only the lines

https://github.com/tree-sitter/tree-sitter-c/blob/a2b7bac3b313efbaa683d9a276ff63cdc544d960/grammar.js#L1194-L1195
need to be changed to
```javascript
identifier: _ =>
      /(\p{XID_Start}|_|\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8}|\$)(\p{XID_Continue}|\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8}|\$)*/,
```

**Comment by amaanq** [comment]
Done on master
