### ISSUE TITLE
different highlight result of typedef

### ISSUE THREAD

**Issue by Freed-Wu** [tree-sitter/tree-sitter-c#167]
Install [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), then `vi /usr/include/linux/types.h`:

![screen-2023-10-01-20-26-02](https://github.com/tree-sitter/tree-sitter-c/assets/32936898/840b0229-b42b-4050-96f5-b34ee036f16c)
Why `__poll_t` is not highlighted as `__le16`? Is it a bug?

**Comment by amaanq** [comment]
Because __bitwise is a macro, expanding it parses fine, sorry tree-sitter isn't context aware to know that.

**Comment by Freed-Wu** [comment]
Hey, what is `tsa` in your screenshot?
