### ISSUE TITLE
Error with: STB style header

### ISSUE THREAD

**Issue by ayoubelmhamdi** [tree-sitter/tree-sitter-c#169]
```c
#ifndef CREQUEST_H_
#define CREQUEST_H_

#include <stdio.h>

#endif // CREQUEST_H_



#ifdef CREQUEST_IMPLEMENTATION
void f(){}
#endif // CREQUEST_IMPLEMENTATION
```
This c code as stb style library does not work for me, it's failed in `#ifdef CREQUEST_IMPLEMENTATION`, can anyone test it in Neovim.
<p align="center">
  <img width="460"  src="https://github.com/tree-sitter/tree-sitter-c/assets/34358145/29594bff-c430-4559-a58f-8e7a9cddbcff">
</p>

**Comment by amaanq** [comment]
wrong repo, belongs in nvim-treesitter
