### ISSUE TITLE
Assignment with pointer increment leads to an error

### ISSUE THREAD

**Issue by calixteman** [tree-sitter/tree-sitter-c#20]
For example
```c
void foo() {
  *p++ = 1;
}
```

**Comment by maxbrunsfeld** [comment]
Oh, it looks like we have the precedence wrong for pointer expressions (`*`) vs unary math expressions (`++`). Right now, the parser probably thinks that the pointer expression is *inside* of the unary math expression. Pointer expressions should probably have lower precedence than unary math expressions.

**Comment by calixteman** [comment]
I've a fix in adding math_expression in assignment_expression but I'm not sure that's a good idea.

**Comment by maxbrunsfeld** [comment]
I think this was fixed by #21.
