### ISSUE TITLE
bug: LF EOL settings in .gitattributes affecting test/corpus/crlf.txt

### ISSUE THREAD

**Issue by ribru17** [tree-sitter/tree-sitter-c#200]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.21.0 (1c55abb5308fe3891da545662e5df7ba28ade275)

### Describe the bug

The `eol=lf` setting in `.gitattributes` causes the CRLF endings in `test/corpus/crlf.txt` to be overridden.

### Steps To Reproduce/Bad Parse Tree

NA

### Expected Behavior/Parse Tree

NA

### Repro

```C
NA
```

**Comment by Thaodan** [comment]
Commit at fault is:
https://github.com/tree-sitter/tree-sitter-c/commit/db11e9188940f2b99128635d53876ac040c8f8c3

**Comment by amaanq** [comment]
@ObserverOfTime

**Comment by ObserverOfTime** [comment]
Set `eol=crlf` on any files that require it.

**Comment by Thaodan** [comment]
Don't set gittattributes to enforce file stypes, doing so is sort of a hack since you edit files outside of git comment operations.

Please don't commit built artifacts to repositories..

**Comment by Thaodan** [comment]
Also checking out the last release fails because of the gittattribute being present.
