### ISSUE TITLE
bug: Discrepancy between parse and playground trees

### ISSUE THREAD

**Issue by SunBK201** [tree-sitter/tree-sitter-c#211]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Describe the bug

I found that the output of tree-sitter-c is inconsistent with that of playground c. Just like https://github.com/tree-sitter/tree-sitter/issues/3449.

I use pypi https://pypi.org/project/tree-sitter-c to parse the C code. There is an error node, but there is no such error node in the [playground](https://tree-sitter.github.io/tree-sitter/playground):

```c
err = route4_set_parms(net, tp, base, f, handle, head, tb, tca[TCA_RATE], new, flags, extack);
```

In addition, I found that the parsing error of using pypi https://pypi.org/project/tree-sitter-c is consistent with the parsing error of using pypi https://pypi.org/project/tree-sitter-cpp. Does this mean that tree-sitter-c and tree-sitter-cpp in pypi use the [cpp parser](https://github.com/tree-sitter/tree-sitter-cpp) at the same time?

### Steps To Reproduce/Bad Parse Tree

```c
err = route4_set_parms(net, tp, base, f, handle, head, tb, tca[TCA_RATE], new, flags, extack);
```

ERROR NODE: `,` (behind `new`)

### Expected Behavior/Parse Tree

```c
err = route4_set_parms(net, tp, base, f, handle, head, tb, tca[TCA_RATE], new, flags, extack);
```

This code should have no error nodes in tree-sitter-c.

### Repro

```C
err = route4_set_parms(net, tp, base, f, handle, head, tb, tca[TCA_RATE], new, flags, extack);
```

**Comment by SunBK201** [comment]
@amaanq Does pypi [tree-sitter-c](https://pypi.org/project/tree-sitter-c) use [tree-sitter-cpp](https://github.com/tree-sitter/tree-sitter-cpp) parser?

**Comment by amaanq** [comment]
no, and the latest version does not have this issue
