### ISSUE TITLE
bug: Misparsing asm attribute

### ISSUE THREAD

**Issue by ashamedbit** [tree-sitter/tree-sitter-c#224]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.22.3

### Describe the bug

Treesitter fails to parse asm attribute within code.

### Steps To Reproduce/Bad Parse Tree

int main(){
__asm__ __volatile__("" : "+r" (dst16));
}

### Expected Behavior/Parse Tree
[translation_unit](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [3, 0]
  [function_definition](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [2, 1]
    type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [0, 3]
    declarator: [function_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [0, 4] - [0, 10]
      declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 4] - [0, 8]
      parameters: [parameter_list](https://tree-sitter.github.io/tree-sitter/playground#) [0, 8] - [0, 10]
    body: [compound_statement](https://tree-sitter.github.io/tree-sitter/playground#) [0, 10] - [2, 1]
      [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [1, 7]
      [expression_statement](https://tree-sitter.github.io/tree-sitter/playground#) [1, 8] - [1, 40]
        [call_expression](https://tree-sitter.github.io/tree-sitter/playground#) [1, 8] - [1, 39]
          function: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 8] - [1, 20]
          arguments: [argument_list](https://tree-sitter.github.io/tree-sitter/playground#) [1, 20] - [1, 39]
            [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [1, 21] - [1, 25]
              [string_literal](https://tree-sitter.github.io/tree-sitter/playground#) [1, 21] - [1, 23]
            [call_expression](https://tree-sitter.github.io/tree-sitter/playground#) [1, 26] - [1, 38]
              function: [string_literal](https://tree-sitter.github.io/tree-sitter/playground#) [1, 26] - [1, 30]
                [string_content](https://tree-sitter.github.io/tree-sitter/playground#) [1, 27] - [1, 29]
              arguments: [argument_list](https://tree-sitter.github.io/tree-sitter/playground#) [1, 31] - [1, 38]
                [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 32] - [1, 37]
          
 There should be no error nodes in the AST tree.

### Repro
```C
int main(){
__asm__ __volatile__("" : "+r" (dst16));
}
```

**Comment by amaanq** [comment]
your quotes are not normal quotes but rather U+201C and U+201D

**Comment by ashamedbit** [comment]
The error still persists with the normal quotes due to the asm identifier
