### ISSUE TITLE
bug: Double ; results in treesitter misparse

### ISSUE THREAD

**Issue by ashamedbit** [tree-sitter/tree-sitter-c#227]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.23.0

### Describe the bug

When double semicolon is used succesively, treesitter has error nodes.

### Steps To Reproduce/Bad Parse Tree

struct client_file *client_files_RB_MINMAX(struct client_files *, int);;

[translation_unit](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [1, 0]
  [declaration](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [0, 71]
    type: [struct_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [0, 18]
      name: [type_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 7] - [0, 18]
    declarator: [pointer_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [0, 19] - [0, 70]
      declarator: [function_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [0, 20] - [0, 70]
        declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 20] - [0, 42]
        parameters: [parameter_list](https://tree-sitter.github.io/tree-sitter/playground#) [0, 42] - [0, 70]
          [parameter_declaration](https://tree-sitter.github.io/tree-sitter/playground#) [0, 43] - [0, 64]
            type: [struct_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 43] - [0, 62]
              name: [type_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 50] - [0, 62]
            declarator: [abstract_pointer_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [0, 63] - [0, 64]
          [parameter_declaration](https://tree-sitter.github.io/tree-sitter/playground#) [0, 66] - [0, 69]
            type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [0, 66] - [0, 69]
  [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [0, 71] - [0, 72]
### Expected Behavior/Parse Tree

There should be no error nodes on inserting 2 semicolons as it is valid C code

### Repro

```C
struct client_file *client_files_RB_MINMAX(struct client_files *, int);;
```

**Comment by ObserverOfTime** [comment]
Note: This only occurs when the extra semicolon is not inside a block.
