### ISSUE TITLE
bug: Error nodes when initializing struct array 

### ISSUE THREAD

**Issue by ashamedbit** [tree-sitter/tree-sitter-c#228]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.23.0

### Describe the bug

Parsing error when a struct array is defined ( whose values are populated by other function calls)

### Steps To Reproduce/Bad Parse Tree

[translation_unit](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [13, 0]
  [struct_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [2, 1]
    name: [type_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 7] - [0, 18]
    body: [field_declaration_list](https://tree-sitter.github.io/tree-sitter/playground#) [0, 19] - [2, 1]
      [field_declaration](https://tree-sitter.github.io/tree-sitter/playground#) [1, 1] - [1, 10]
        type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [1, 1] - [1, 4]
        declarator: [field_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 5] - [1, 9]
  [struct_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [4, 0] - [7, 1]
    name: [type_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [4, 7] - [4, 19]
    body: [field_declaration_list](https://tree-sitter.github.io/tree-sitter/playground#) [4, 20] - [7, 1]
      [field_declaration](https://tree-sitter.github.io/tree-sitter/playground#) [5, 1] - [5, 8]
        type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [5, 1] - [5, 4]
        declarator: [field_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [5, 5] - [5, 7]
      [field_declaration](https://tree-sitter.github.io/tree-sitter/playground#) [6, 1] - [6, 10]
        type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [6, 1] - [6, 4]
        declarator: [field_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [6, 5] - [6, 9]
  [declaration](https://tree-sitter.github.io/tree-sitter/playground#) [8, 0] - [10, 2]
    [storage_class_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [8, 0] - [8, 6]
    [type_qualifier](https://tree-sitter.github.io/tree-sitter/playground#) [8, 7] - [8, 12]
    type: [struct_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [8, 13] - [8, 31]
      name: [type_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [8, 20] - [8, 31]
    declarator: [init_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [8, 32] - [10, 1]
      declarator: [array_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [8, 32] - [8, 47]
        declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [8, 32] - [8, 45]
      value: [initializer_list](https://tree-sitter.github.io/tree-sitter/playground#) [8, 50] - [10, 1]
        [initializer_list](https://tree-sitter.github.io/tree-sitter/playground#) [9, 1] - [9, 92]
          [cast_expression](https://tree-sitter.github.io/tree-sitter/playground#) [9, 3] - [9, 37]
            type: [type_descriptor](https://tree-sitter.github.io/tree-sitter/playground#) [9, 4] - [9, 18]
              type: [sized_type_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [9, 4] - [9, 18]
            value: [parenthesized_expression](https://tree-sitter.github.io/tree-sitter/playground#) [9, 19] - [9, 37]
              [binary_expression](https://tree-sitter.github.io/tree-sitter/playground#) [9, 20] - [9, 36]
                left: [binary_expression](https://tree-sitter.github.io/tree-sitter/playground#) [9, 20] - [9, 30]
                  left: [number_literal](https://tree-sitter.github.io/tree-sitter/playground#) [9, 20] - [9, 24]
                  right: [number_literal](https://tree-sitter.github.io/tree-sitter/playground#) [9, 26] - [9, 30]
                right: [number_literal](https://tree-sitter.github.io/tree-sitter/playground#) [9, 32] - [9, 36]
          [number_literal](https://tree-sitter.github.io/tree-sitter/playground#) [9, 39] - [9, 40]
          [number_literal](https://tree-sitter.github.io/tree-sitter/playground#) [9, 42] - [9, 43]
          [call_expression](https://tree-sitter.github.io/tree-sitter/playground#) [9, 45] - [9, 90]
            function: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [9, 45] - [9, 63]
            arguments: [argument_list](https://tree-sitter.github.io/tree-sitter/playground#) [9, 63] - [9, 90]
              [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [9, 64] - [9, 70]
                [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [9, 64] - [9, 70]
              [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [9, 71] - [9, 83]
              [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [9, 85] - [9, 89]

### Expected Behavior/Parse Tree

No error nodes on parsing the provided initialized struct array. It is compilable C code.

### Repro

```C
struct sock_filter {
 int code;
};

struct seccomp_data {
 int nr;
 int arch;
};
static const struct sock_filter preauth_insns[] = {
 { (unsigned short)(0x00 +0x00 +0x20), 0, 0, __builtin_offsetof(struct seccomp_data, arch) },
};
```

**Comment by ObserverOfTime** [comment]
Same underlying issue as #229.
