### ISSUE TITLE
bug: Error nodes on parsing string with escape sequence in it

### ISSUE THREAD

**Issue by ashamedbit** [tree-sitter/tree-sitter-c#231]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.23.0

### Describe the bug

Initializing a string with something like "\x" leads to treesitter throwing error nodes.

### Steps To Reproduce/Bad Parse Tree

[translation_unit](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [3, 0]
  [function_definition](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [2, 1]
    type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [0, 3]
    declarator: [function_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [0, 4] - [0, 10]
      declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 4] - [0, 8]
      parameters: [parameter_list](https://tree-sitter.github.io/tree-sitter/playground#) [0, 8] - [0, 10]
    body: [compound_statement](https://tree-sitter.github.io/tree-sitter/playground#) [0, 10] - [2, 1]
      [declaration](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [1, 19]
        type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [1, 4]
        declarator: [init_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [1, 5] - [1, 17]
          declarator: [array_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [1, 5] - [1, 10]
            declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 5] - [1, 6]
            size: [number_literal](https://tree-sitter.github.io/tree-sitter/playground#) [1, 7] - [1, 9]
          [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [1, 13] - [1, 15]
            [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [1, 14] - [1, 15]
          value: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 15] - [1, 17]
        [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [1, 17] - [1, 19]
          [string_content](https://tree-sitter.github.io/tree-sitter/playground#) [1, 18] - [1, 19]
        [MISSING ;](https://tree-sitter.github.io/tree-sitter/playground#) [1, 19] - [1, 19]

### Expected Behavior/Parse Tree

Parsed tree contains error nodes even though the code is compilable.

### Repro

```C
int main(){
   char e[10] = "\x3";
}
```

**Comment by ObserverOfTime** [comment]
Note: https://en.wikipedia.org/wiki/Escape_sequences_in_C#Hex
