### ISSUE TITLE
bug: Using __attribute((noreturn)) leads to error nodes later on.

### ISSUE THREAD

**Issue by ashamedbit** [tree-sitter/tree-sitter-c#233]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.23.0

### Describe the bug

Using __attribute((noreturn)) leads to misparsing later on.

### Steps To Reproduce/Bad Parse Tree

[translation_unit](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [6, 0]
  [function_definition](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [4, 1]
    [storage_class_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [1, 6]
    type: [primitive_type](https://tree-sitter.github.io/tree-sitter/playground#) [1, 7] - [1, 11]
    declarator: [function_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [1, 12] - [2, 57]
      declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 12] - [1, 23]
      parameters: [parameter_list](https://tree-sitter.github.io/tree-sitter/playground#) [1, 23] - [1, 35]
        [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [1, 24] - [1, 34]
          [type_qualifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 25] - [1, 33]
      [call_expression](https://tree-sitter.github.io/tree-sitter/playground#) [2, 0] - [2, 57]
        function: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 0] - [2, 9]
        arguments: [argument_list](https://tree-sitter.github.io/tree-sitter/playground#) [2, 9] - [2, 57]
          [binary_expression](https://tree-sitter.github.io/tree-sitter/playground#) [2, 10] - [2, 34]
            left: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 10] - [2, 26]
            right: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 28] - [2, 34]
          [binary_expression](https://tree-sitter.github.io/tree-sitter/playground#) [2, 36] - [2, 51]
            left: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 36] - [2, 41]
            [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [2, 42] - [2, 46]
              [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 42] - [2, 46]
            right: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 48] - [2, 51]
          [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [2, 51] - [2, 56]
    body: [compound_statement](https://tree-sitter.github.io/tree-sitter/playground#) [3, 0] - [4, 1]

### Expected Behavior/Parse Tree

There should not be any error nodes in parse tree.

### Repro

```C
static void __attribute((noreturn))
bpf_error(compiler_state_t *cstate, const char *fmt, ...)
{
}
```

**Comment by ObserverOfTime** [comment]
It's `__attribute__`

**Comment by ashamedbit** [comment]
Hello @ObserverOfTime. The following code with __attribute(noreturn)) should be perfectly compilable C code:

```
struct compiler_state_t
{
    int x;
};
typedef struct compiler_state_t compiler_state_t;
static void __attribute((noreturn))
bpf_error(compiler_state_t *cstate, const char *fmt, ...)
{
}
int main()
{
    return 0;
}
```
I belive this is a valid bug because this compilable code snippet produces treesitter bugs.

**Comment by ObserverOfTime** [comment]
Can you find a formal definition of `__attribute`, as opposed to `__attribute__`?

**Comment by ashamedbit** [comment]
I believe it is shorthand for __attribute. Also both gcc and clang can compile the same code.
