### ISSUE TITLE
bug: Neovim hangs with 100% CPU usage when editing function pointers

### ISSUE THREAD

**Issue by olzhasar** [tree-sitter/tree-sitter-c#242]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-c

### Describe the bug

My editor keeps freezing whenever I try to rename a function pointer. The issue goes away when disabling treesitter C parser.

### Steps To Reproduce/Bad Parse Tree

typedef struct foo {
  int (*bar)(void *obj);
} foo;

try to rename the pointer bar with `ciw`

### Expected Behavior/Parse Tree

-

### Repro

```C
// Example code that causes the issue
void foo() {
  // Code that fails to parse, or causes an error
}
```

**Comment by amaanq** [comment]
check nvim-treesitter issues.

**Comment by olzhasar** [comment]
Ok. This happens only in C though, that's why I assumed the problem is in the parser
