### ISSUE TITLE
Line comments with \n are incorrectly parsed

### ISSUE THREAD

**Issue by simonrepp** [tree-sitter/tree-sitter-c#30]
In Atom, given any line of the form `// ...\n...` in a C file, both the `\n` and the following characters don't show up as part of the comment anymore, which is what I would expect.

- I've made sure tree-sitter is enabled for syntax highlighting in Atom's core settings
- I inspected the `language-c` package (`tree-sitter-c.cson` specifically), which looks fine (therefore I assume the problem is in the tree-sitter grammar itself)
- This also affects C++ (`tree-sitter-cpp`)

![Screenshot from 2019-08-03 09-43-36](https://user-images.githubusercontent.com/13210/62409222-5711f680-b5d4-11e9-8e80-cddbfc2e7e39.png)
(Note: I did the scope inspection in this screenshot backwards, from top to bottom: `bar`, `\n`, `// foo`)

![Screenshot from 2019-08-03 09-41-20](https://user-images.githubusercontent.com/13210/62409378-8b86b200-b5d6-11e9-801a-ba7c17509698.png)

**Comment by maxbrunsfeld** [comment]
I think this is fixed. Thanks for the report!

**Comment by simonrepp** [comment]
Indeed it is, fix confirmed. Thanks a lot!
