### ISSUE TITLE
tree-sitter.exe test fails: Failed to execute C compiler

### ISSUE THREAD

**Issue by blueyed** [tree-sitter/tree-sitter-c#33]
This happens on AppVeyor with Neovim's PR to upgrade LuaRocks, where it is
required to set `VCINSTALLDIR` to work around an issue in LuaRocks.

```
DEBUG:  119+  >>>> c:\treesitter\tree-sitter.exe --help
tree-sitter 0.15.9 (0795b59695854505e74e1dd70f48bbbd1a354414)
Max Brunsfeld <maxbrunsfeld@gmail.com>
Generates and tests parsers

USAGE:
    tree-sitter.exe <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    build-wasm        Compile a parser to WASM
    dump-languages    Print info about all known language parsers
    generate          Generate a parser
    help              Prints this message or the help of the given subcommand(s)
    highlight         Highlight a file
    init-config       Generate a default config file
    parse             Parse files
    query             Search files using a syntax tree query
    test              Run a parser's tests
    web-ui            Test a parser interactively in the browser
DEBUG:  120+  >>>> c:\treesitter\tree-sitter.exe test

Failed to execute C compiler
Details:
  The system cannot find the file specified. (os error 2)

```

I've changed it now, but it still causes the above error.

```diff
-  $env:VCINSTALLDIR = "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/"
+  $env:VCINSTALLDIR = "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/"
```

I'll try to unset it before running "tree-sitter.exe test" now, but thought
that it would be good to have more details with the error there in any case.

**Comment by maxbrunsfeld** [comment]
Thanks for the report.

This is more of an issue with the `tree-sitter` command line tool, as opposed to the C language parser. I am not very familiar with MSVC and the windows C++ toolchain, but I think the relevant code is [in the `cc-rs`](https://github.com/alexcrichton/cc-rs/blob/02ed9e6895c6524afa23caa2ac1d2b48d1739e0a/src/windows_registry.rs#L64-L74) crate, which `tree-sitter` uses to compile C code.

From that code, it looks like the expectation is that if `VCINSTALLDIR` is set to a certain windows SDK, then the `PATH`, `INCLUDE`, `LIB`, and `LIBPATH` variables should *also* be set up to use the corresponding SDK.

**Comment by blueyed** [comment]
Interesting.  Maybe we / AppVeyor should run `vcvars` then in the first place?
As for Neovim: I'm only setting it now later for the LuaRocks workaround.

**Comment by maxbrunsfeld** [comment]
Ok, I'm going to close this one out, since I don't think there's an issue with the C parser. If anyone is aware of some potential improvements to the way that Tree-sitter (or `cc-rs`) detects the Windows SDK and its associated libraries, feel free to open an issue on `tree-sitter/tree-sitter` and/or `cc-rs`.
