### ISSUE TITLE
Include a list of repositories/projects tree-sitter-c was tested with

### ISSUE THREAD

**Issue by icsaszar** [tree-sitter/tree-sitter-c#50]
It would be useful to have a list of repos and their parsing status, similar to the "Java grammar finish line" here https://github.com/tree-sitter/tree-sitter-java/issues/27.

I've tried following repositories using the `"(ERROR) @error"` query and all of them contain parsing errors:

[craftinginterpreters](https://github.com/munificent/craftinginterpreters)
[grep](https://git.savannah.gnu.org/git/grep.git/)
[jemalloc](https://github.com/jemalloc/jemalloc)
[ncurses](https://github.com/gittup/ncurses)
[neovim](https://github.com/neovim/neovim)
[nginx](https://github.com/nginx/nginx)
[oniguruma](https://github.com/kkos/oniguruma)
[redis](https://github.com/redis/redis)
[the_silver_searcher](https://github.com/ggreer/the_silver_searcher)
[transmission](https://github.com/transmission/transmission)
[wren](https://github.com/wren-lang/wren)
[wrk](https://github.com/wg/wrk)
[zstd](https://github.com/facebook/zstd)

I'll try to clean up my testing code and post it here soon.

**Comment by icsaszar** [comment]
I finally got around to it, here's repo with the code I used for testing these repositories https://github.com/icsaszar/tree-sitter-c-parsing.

**Comment by milahu** [comment]
> all of them contain parsing errors

excluding parse-errors is not enough to find all bugs

we should compare the parse-tree to some reference, for example clang

```
clang -fsyntax-only -Xclang -ast-dump=json -Xclang -ast-dump-filter=some_function some_source.cc
```

obviously the parse-tree has a different format, but it should be possible to write an adapter
