### ISSUE TITLE
#defines with a multiline comment fails

### ISSUE THREAD

**Issue by n5m** [tree-sitter/tree-sitter-c#55]
```c
#define DONTCARE 16 /* comment /*
```
correctly parses into
```
Syntax tree: (translation_unit (preproc_def name: (identifier) value: (preproc_arg)))
```
using [the example program from the documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#an-example-program).

But parsing fails when the comment is a multiline comment.
```c
#define DONTCARE 16 /* multiline
comment /*
```
The result is
```
Syntax tree: (translation_unit (preproc_def name: (identifier) value: (preproc_arg)) (ERROR (identifier)))
```

**Comment by jyapayne** [comment]
Not sure if you just typed it wrong here, but shouldn't the multiline comment be: 

```c
#define DONTCARE 16 /* multiline
comment */
```

(Notice the end of the multiline comment has been updated to have the `*` and `/` swapped)

**Comment by n5m** [comment]
Closing as duplicate of #44
