### ISSUE TITLE
initializer_pair parsing multiple nodes into non-multiple field

### ISSUE THREAD

**Issue by berchn** [tree-sitter/tree-sitter-c#57]
The `initializer_pair` rule accepts many `subscript_designator`s and `field_designator`s into the `designator` field. This lines up with the rule in grammar.json, but the respective node type for `initializer_pair` specifies `"multiple": false` for the `designator` field. Is this intended?

**Comment by maxbrunsfeld** [comment]
This sounds like a bug. I’ll try regenerating with the latest Tree-sitter. There have been some changes to the node-types logic.

**Comment by berchn** [comment]
Thanks!

**Comment by maxbrunsfeld** [comment]
It looks like this is fixed by https://github.com/tree-sitter/tree-sitter-c/commit/8d4631b673f8a9d968d1d93393c0a965194abac0.
