### ISSUE TITLE
Incorrect Unnamed Node Range

### ISSUE THREAD

**Issue by berchn** [tree-sitter/tree-sitter-c#66]
I'm using this string: `"#define a \n"`. The following is a list representation of the parse tree including the unnamed nodes:
```lisp
(:TRANSLATION-UNIT ((0 0) (0 1))
 ((:PREPROC-DEF ((0 0) (0 1))
   ((:|#DEFINE| ((0 0) (7 0)) NIL)
    ((:NAME :IDENTIFIER) ((8 0) (9 0)) NIL)
    (:|
|
     ((9 0) (0 1)) NIL)))))
```
In the parse tree, the newline starts at (9 0), but in the provided string above, the space after the `a` is at (9 0) and the newline is at (10 0). Is this behavior expected?

**Comment by amaanq** [comment]
Fixed on master
