### ISSUE TITLE
'assignment_expression' Doesn't Store the Assignment Operator

### ISSUE THREAD

**Issue by berchn** [tree-sitter/tree-sitter-c#67]
'assignment_expression' doesn't store enough information to determine what the node is representing. To address this, a 'FIELD' could be added around the assignment operation similar to how 'binary_expression' stores its operation.

**Comment by maxbrunsfeld** [comment]
Good idea. Want to open a PR?

**Comment by berchn** [comment]
Yeah, I'll open one when I have a chance.
