### ISSUE TITLE
Tree-sitter doesn't understand c-macros

### ISSUE THREAD

**Issue by H-C-H** [tree-sitter/tree-sitter-c#7]
First of all, I just recently found out about tree-sitter and am super-excited about this project!

I opened one of my existing c-projects with code similar to the example below. Tree-sitter cannot handle the following use/abuse of macros. The code is only syntactically correct after macro expansion. The screenshot below illustrates the issue (highlighted in green).

<img width="295" alt="image" src="https://user-images.githubusercontent.com/31404215/40426017-4a444fc6-5e9a-11e8-850a-d865f2951278.png">

Here is the full code
```c
/*
A dummy bytecode interpreter code fragment.

outputs the following:
        1 + 2 = 3
        4 - 5 = -1
        7 < 8 = 1
        10 > 11 = 0
        bye
 */

#include <stdio.h>

enum opcode {
  OP_ADD = 0,
  OP_SUB = 3,
  OP_LT = 6,
  OP_GT = 9,
};

// dummy instruction sequence
int decode()
{
    static int i = 0;
    return i++;
}

#define BINARY(op)                                                             \
    do {                                                                       \
        int a = decode();                                                      \
        int b = decode();                                                      \
        printf("%d " #op " %d = %d\n", a, b, a op b);                          \
    } while (0);

void exec()
{
    while (1) {
        enum opcode code = 
            (enum opcode) decode();
        switch (code) {
        case OP_ADD:
            BINARY(+);
            break;
        case OP_SUB:
            BINARY(-);
            break;
        case OP_LT:
            BINARY(<);
            break;
        case OP_GT:
            BINARY(>);
            break;
        default:
            puts("bye");
            return;
        }
    }
}

int main() { exec(); }
```

Atom reports:
Scopes at Cursor:
- c
- translation_unit
- function_definition
- compound_statement
- while_statement
- compound_statement
- switch_statement
- compound_statement
- case_statement
- expression_statement
- ERROR
- system_lib_string

Atom version:
1.27.1

**Comment by maxbrunsfeld** [comment]
I'm gonna close this one out because I think we're doing the best we can under our constraints. Error recovery may improve more in the future, but the basic paradigm probably won't change.
