### ISSUE TITLE
Doesn't parse variadic function declarations.

### ISSUE THREAD

**Issue by XVilka** [tree-sitter/tree-sitter-c#73]
See simplest case of `printf`-like function:
```c
void print(char *, ...);
```
It returns the following tree:
```
translation_unit [0, 0] - [1, 0]
  declaration [0, 0] - [0, 24]
    type: primitive_type [0, 0] - [0, 4]
    declarator: function_declarator [0, 5] - [0, 23]
      declarator: identifier [0, 5] - [0, 10]
      parameters: parameter_list [0, 10] - [0, 23]
        parameter_declaration [0, 11] - [0, 17]
          type: primitive_type [0, 11] - [0, 15]
          declarator: abstract_pointer_declarator [0, 16] - [0, 17]
```
As you can see, it stops on `char *` and doesn't indicate there is one more parameter after it.

**Comment by maxbrunsfeld** [comment]
It parses it, but the node for the `...` token is not given a name. I think we should just extract [the `...` token](https://github.com/tree-sitter/tree-sitter-c/blob/008008e30a81849fca0c79291e2b480855e0e02c/grammar.js#L553) to a separate named rule called `variadic_parameter` or something.

**Comment by XVilka** [comment]
Yes, that would be perfect.
