### ISSUE TITLE
Error parsing preprocessor statements with a space in front after stubbed macros

### ISSUE THREAD

**Issue by pluick** [tree-sitter/tree-sitter-c#85]
I'm noticing a misparse when a #define is preceded by a space.

    #define MACRO_STUB
    #define MACRO x
yields this parse:
`(translation_unit (preproc_def name: (identifier)) (preproc_def name: (identifier) value: (preproc_arg)))`

but if I insert a space before the second #define like this:

    #define MACRO_STUB
     #define MACRO x
yields this (incorrect) parse:
`(translation_unit (preproc_def name: (identifier) value: (preproc_arg)))`

Notably, the parser still produces correct output if the first macro is not stubbed:

    #define MACRO_NOSTUB x
     #define MACRO x
`(translation_unit (preproc_def name: (identifier) value: (preproc_arg)) (preproc_def name: (identifier) value: (preproc_arg)))`
I tried like one change so far that didn't work (since I don't understand the parser well), changing preproc_arg to:
`preproc_arg: $ => token(prec(-1, repeat1(/[^\n]|\\\r?\n/))),`

**Comment by alemuller** [comment]
Have you consider implementing the preproc directives as `extras`? They can be legally used in uncountable ways.

Another example that ts-c fails to parse:

```c
const char foo[] {
 #include "filename"
};
```

**Comment by amachronic** [comment]
In the extreme case, a preproc directive can occur between any two tokens. I think putting them in `extras` is the only correct solution.

@pluick -- It seems comment tokens are returned by tree-sitter, there is even a test case (`extra_non_terminals`) in the tree-sitter repo which shows them being returned despite being in `extras`. Otherwise, every editor using tree-sitter for syntax highlighting must be using language-specific hacks for highlighting comments...

**Comment by alemuller** [comment]
@maxbrunsfeld are you with the macros (and attributes?) being described as `extra`? I can make a PR if approve the idea.

Another option is to implement the directives as a external language, since there are a few languages that share the same syntax (yacc, bison, gcc's md, etc).

**Comment by maxbrunsfeld** [comment]
It's useful to include some preprocessor directives (like `#if`/`#else`, etc) in the main grammar, because we want those constructs represented structurally in the syntax tree, which allow you to do things like code folding of `#if` in a text editor.

Maybe some other preprocessor directives would be better handled as non-terminal extras though.

**Comment by pluick** [comment]
I've come up with 2 possible solutions. The original solution I posted above still fixes my issue, and I couldn't find any regressions with it:
`preproc_arg: $ => token.immediate(prec(-1, repeat1(/[^\n]|\\\r?\n/))),`

Then I tried to come up with something to handle comments after macros (they are currently parsed as a part of the macro).
`preproc_arg: $ => token.immediate(prec(-1, repeat1(/[^\n\/]|\/[^*\/]|\\\r?\n/))),`
Which parses the examples in #59 correctly, except for one case that I created:
    #define MACRO \
    { \
    	statment = y; /* comment */ \
    }
`(ERROR (identifier) (preproc_arg) (comment))`

I guess the decision goes to @maxbrunsfeld , which change do you want? The one that fixes only this issue or the one with a regression?

**Comment by amachronic** [comment]
I'd just like to point out an example:
```c
void f() {
#if A
    if(x) {
#else
    if(y) {
#endif
        blech();
    }
}
```
There are two versions of the file -- both are syntactically valid, but it's impossible to combine both versions in a way that fits the grammar. I suppose this could be handled by treating the different branches as ambiguities but tree-sitter isn't designed to parse ambiguous grammars, is it?

If a 'perfect' parse is impossible, maybe the preprocessor aspect of the C/C++ grammars should be designed with that in mind.

**Comment by benjaminBrownlee** [comment]
This conversation looks like it went in another direction, but does #133 fix the original issue?

**Comment by amaanq** [comment]
I'll assume yes as the given example parses fine, do comment if it doesn't though
