### ISSUE TITLE
Highlight different with builtin types.

### ISSUE THREAD

**Issue by jackhub** [tree-sitter/tree-sitter-c#90]
I would like to highlight builtin types differently from user defined types. Like `int` type here:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/4580635/149303245-bbda38f4-3a6b-4e11-a7ff-db9b374971ea.png">

But tree-sitter-c will highlight to a Normal type.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/4580635/149303336-cd17af68-c1bb-47d8-8c7f-cd480fa31cdc.png">

PS: std::vector is highlight by lsp semantic token.

**Comment by jrwrigh** [comment]
This is the wrong tree sitter for C++. You want: https://github.com/tree-sitter/tree-sitter-cpp
