### ISSUE TITLE
Querying function paramter lists fails

### ISSUE THREAD

**Issue by schirrmacher** [tree-sitter/tree-sitter-c#93]
When querying for function parameter lists, I had the following issue:

```
static inline int some_function(struct slab *slab)
{
}

void __init some_other_function(void)
{
}
```

In this example only `(struct slab *slab)` is matched. I think the parser has problems with `__init`. 

Is this intended behavior? Can I somehow extend the parser?

**Comment by maxbrunsfeld** [comment]
What is the query that you're using?

**Comment by schirrmacher** [comment]
`(function_definition _) @function`

**Comment by schirrmacher** [comment]
![Screenshot 2022-02-23 at 16 58 21](https://user-images.githubusercontent.com/6545822/155356881-5474548f-ae6c-4058-aea6-3d6b60efea18.png)

**Comment by amaanq** [comment]
seems like this is fixed now
