### ISSUE TITLE
No support for C11 AltId Unicode identifiers

### ISSUE THREAD

**Issue by rurban** [tree-sitter/tree-sitter-c#94]

**Comment by amaanq** [comment]
An example would be nice

**Comment by dundargoc** [comment]
No examples given. Closing. Can reopen when example given.

**Comment by rurban** [comment]
See the C11 and C23 identifier definitions, which unicode characters are allowed.
E.g. this code
```C
#include <assert.h>
int main() {
  int a = 2; // which is which?
  int а = 3;
  assert(a == 2);  // OK
  assert(а == 3);  // OK
  return 0;
}
```
is valid C11.
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3146.html lists the ranges.

**Comment by amaanq** [comment]
That code parses just fine.
