### ISSUE TITLE
No support for C23 xid/tr31 Unicode ranges

### ISSUE THREAD

**Issue by rurban** [tree-sitter/tree-sitter-c#95]

**Comment by maxbrunsfeld** [comment]
Could you provide a code example, a description of the parse tree  you'd expect, and a link to the description of the language feature in question?

**Comment by rurban** [comment]
The C23 changes are described here http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1949r7.html

it's basically XID (as in most other languages) with additional NFC requirement

**Comment by amaanq** [comment]
Should be fixed on master
